include:
  - services/mark-service/docker-compose.yml

services:
  traefik:
    image: traefik:v2.11
    environment:
      - DOCKER_API_VERSION=1.45
    ports:
      - "82:82"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /etc/letsencrypt/live/realtimemap.ru:/certs:ro
    networks:
      - web

networks:
  web:
    external: true