ENV: "dev"

database:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  db_name: "db_name"

kafka:
  brokers:
    - "localhost:9093"
  topics:
    - "service1.events"
    - "service2.events"
  group_id: "service-service"
  max_wait: "500ms"
  commit_interval: "0"

cacheStrategy: "redis" # memory/redis

redis:
  host: "localhost:6379"

grpc:
  port: 50051

http:
  port: 8082
