api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":82"

log:
  level: DEBUG

accessLog:
  format: common

providers:
  docker:
    exposedByDefault: false
    network: web

http:
  middlewares:
    auth-check:
      forwardAuth:
        address: "http://auth:8001/api/v1/auth/token-validate"
        authResponseHeaders:
          - "X-User-Id"
          - "X-User-Name"
          - "X-User-Admin"